# ---------------------------------------------------------------------------
# 04_plots.R -- figures.
#
# Every figure is written to disk explicitly with ggsave(). The original
# script relied on top-level auto-printing, which means the PNGs in the
# repository had to be exported by hand from the RStudio plot pane -- they
# could not be regenerated by running the script, which is the single biggest
# reproducibility gap in the project.
# ---------------------------------------------------------------------------

#' Build a colour map for whatever series the config specifies.
#' Hard-coding ticker names here was the reason the project was not, in fact,
#' reconfigurable without code changes.
build_palette <- function(series) {
  base <- c("#C0392B", "#2471A3", "#1E8449", "#6C3483", "#D68910",
            "#117A65", "#7B241C", "#5D6D7E", "#884EA0", "#1A5276")
  stats::setNames(rep_len(base, length(series)), series)
}

#' Shared ggplot theme.
theme_fma <- function(base_size = 11) {
  ggplot2::theme_minimal(base_size = base_size) +
    ggplot2::theme(
      plot.title      = ggplot2::element_text(face = "bold", size = base_size + 3),
      plot.subtitle   = ggplot2::element_text(colour = "grey35", size = base_size - 1),
      plot.caption    = ggplot2::element_text(colour = "grey45", size = base_size - 3,
                                              hjust = 0),
      strip.text      = ggplot2::element_text(face = "bold"),
      panel.grid.minor = ggplot2::element_blank(),
      legend.position = "bottom",
      plot.margin     = ggplot2::margin(12, 14, 10, 12)
    )
}

#' Save a figure with consistent dimensions.
save_fig <- function(plot, filename, cfg, width = 10, height = 6.5, dpi = 200) {
  path <- file.path(cfg$figure_dir, filename)
  ggplot2::ggsave(path, plot, width = width, height = height,
                  dpi = dpi, bg = "white")
  log_msg("figure -> ", path)
  invisible(path)
}

#' Shading rectangles for the configured crisis windows.
#' Human-readable list of the shaded crisis windows, taken from the config.
crisis_label <- function(cfg) {
  labs <- vapply(cfg$subperiods, function(sp) sp$label, character(1))
  if (length(labs) == 0) return("")
  paste0("Shaded: ", paste(labs, collapse = " and "), ".")
}

#' @param ymin Lower bound of the shaded band. Must be 0 (not -Inf) on a log
#'   scale: log10(-Inf) is NaN and ggplot warns, whereas log10(0) is -Inf and
#'   clips cleanly.
crisis_layers <- function(cfg, ymin = -Inf) {
  lapply(names(cfg$subperiods), function(nm) {
    sp <- cfg$subperiods[[nm]]
    ggplot2::annotate("rect",
                      xmin = sp$start, xmax = sp$end,
                      ymin = ymin, ymax = Inf,
                      alpha = 0.12, fill = "grey20")
  })
}

#' Cumulative growth of one unit invested, log scale.
plot_cumulative <- function(data, cfg) {
  rets <- data$returns
  wealth <- apply(1 + zoo::coredata(rets), 2, cumprod)
  df <- cbind(data.frame(date = zoo::index(rets)), as.data.frame(wealth))
  long <- tidyr::pivot_longer(df, -date, names_to = "ticker",
                              values_to = "wealth")

  ggplot2::ggplot(long, ggplot2::aes(date, wealth, colour = ticker)) +
    crisis_layers(cfg, ymin = 0) +
    ggplot2::geom_line(linewidth = 0.7) +
    ggplot2::scale_y_log10(labels = scales::label_number(accuracy = 1)) +
    ggplot2::scale_colour_manual(values = build_palette(unique(long$ticker)), name = NULL) +
    ggplot2::labs(
      title    = paste0("Growth of $1, ", sample_label(cfg)),
      subtitle = paste0("Total return, log scale. ", crisis_label(cfg)),
      x = NULL, y = "Cumulative value of $1 (log scale)",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Faceted monthly excess returns.
plot_excess_returns <- function(data, cfg) {
  ex <- data$excess
  df <- cbind(data.frame(date = zoo::index(ex)), as.data.frame(zoo::coredata(ex)))
  long <- tidyr::pivot_longer(df, -date, names_to = "ticker",
                              values_to = "excess")

  ggplot2::ggplot(long, ggplot2::aes(date, excess, colour = ticker)) +
    crisis_layers(cfg) +
    ggplot2::geom_hline(yintercept = 0, colour = "grey60", linewidth = 0.3) +
    ggplot2::geom_line(linewidth = 0.45) +
    ggplot2::facet_wrap(~ ticker, ncol = 1, scales = "free_y") +
    ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    ggplot2::scale_colour_manual(values = build_palette(unique(long$ticker)), guide = "none") +
    ggplot2::labs(
      title    = "Monthly excess returns",
      subtitle = "Return in excess of the one-month risk-free rate.",
      x = NULL, y = "Excess return",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Characteristic line: asset excess return against market excess return.
plot_characteristic_lines <- function(data, cfg) {
  ex  <- data$excess
  mkt <- as.numeric(ex[, data$market_col])

  df <- do.call(rbind, lapply(data$asset_cols, function(a) {
    data.frame(ticker = a, market = mkt, asset = as.numeric(ex[, a]),
               stringsAsFactors = FALSE)
  }))

  ggplot2::ggplot(df, ggplot2::aes(market, asset)) +
    ggplot2::geom_hline(yintercept = 0, colour = "grey80", linewidth = 0.3) +
    ggplot2::geom_vline(xintercept = 0, colour = "grey80", linewidth = 0.3) +
    ggplot2::geom_point(ggplot2::aes(colour = ticker), alpha = 0.45, size = 1.4) +
    ggplot2::geom_smooth(method = "lm", formula = y ~ x,
                         colour = "grey15", linewidth = 0.7, se = TRUE) +
    ggplot2::facet_wrap(~ ticker, ncol = 2) +
    ggplot2::scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
    ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
    ggplot2::scale_colour_manual(values = build_palette(unique(df$ticker)), guide = "none") +
    ggplot2::labs(
      title    = "Characteristic lines",
      subtitle = "Slope = beta, intercept = alpha. Fitted by OLS; reported inference uses Newey-West standard errors.",
      x = paste0(cfg$market_label, " excess return"), y = "Asset excess return",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Rolling beta paths with HAC confidence bands.
#'
#' The bands matter: without them the eye reads every wiggle as a change in
#' systematic risk, when much of it is sampling noise from a 36-month window.
plot_rolling_beta <- function(roll, cfg, stability = NULL) {
  if (is.null(roll)) return(NULL)

  sub <- "Shaded band: 95% HAC confidence interval. Dashed line marks a market beta of 1."
  if (!is.null(stability)) {
    n_sig <- count_beta_breaks(stability, 0.05)
    sub <- paste0(sub, "\nFormal test: ", n_sig, " of ", nrow(stability),
                  " asset-period combinations reject BETA constancy at the 5% level",
                  " (interaction coefficient, HAC; not the joint Chow test).")
  }

  ggplot2::ggplot(roll, ggplot2::aes(date, beta)) +
    crisis_layers(cfg) +
    ggplot2::geom_ribbon(ggplot2::aes(ymin = beta_lo, ymax = beta_hi,
                                      fill = ticker),
                         alpha = 0.20, colour = NA) +
    ggplot2::geom_hline(yintercept = 1, linetype = "dashed",
                        colour = "grey45", linewidth = 0.4) +
    ggplot2::geom_line(ggplot2::aes(colour = ticker), linewidth = 0.7) +
    ggplot2::facet_wrap(~ ticker, ncol = 2) +
    ggplot2::scale_colour_manual(values = build_palette(unique(roll$ticker)),
                                 guide = "none") +
    ggplot2::scale_fill_manual(values = build_palette(unique(roll$ticker)),
                               guide = "none") +
    ggplot2::labs(
      title    = sprintf("Rolling %d-month CAPM beta", cfg$rolling_window_months),
      subtitle = sub,
      x = NULL, y = "Beta",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Estimated beta shift inside each crisis window, with HAC intervals.
plot_beta_shift <- function(stability, cfg) {
  if (is.null(stability)) return(NULL)

  df <- stability
  df$lo <- df$beta_shift - 1.96 * df$shift_se_hac
  df$hi <- df$beta_shift + 1.96 * df$shift_se_hac

  ggplot2::ggplot(df, ggplot2::aes(x = name, y = beta_shift)) +
    ggplot2::geom_hline(yintercept = 0, colour = "grey40", linewidth = 0.4) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lo, ymax = hi),
                           width = 0.15, colour = "grey35") +
    ggplot2::geom_point(size = 2.6, colour = "#2471A3") +
    ggplot2::facet_wrap(~ period, ncol = 1) +
    ggplot2::coord_flip() +
    ggplot2::labs(
      title    = "Change in beta inside each crisis window",
      subtitle = "Interaction coefficient from r - rf = a + b(rm - rf) + cD + d(rm - rf)D.\nIntervals crossing zero mean the shift is not distinguishable from sampling noise.",
      x = NULL, y = "Beta shift (crisis minus rest of sample)",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Correlation heatmap of excess returns.
plot_correlation <- function(data, cfg) {
  cm <- stats::cor(zoo::coredata(data$excess), use = "complete.obs")
  df <- data.frame(as.table(cm), stringsAsFactors = FALSE)
  names(df) <- c("row", "col", "rho")

  ggplot2::ggplot(df, ggplot2::aes(col, row, fill = rho)) +
    ggplot2::geom_tile(colour = "white", linewidth = 1) +
    ggplot2::geom_text(ggplot2::aes(label = sprintf("%.2f", rho)),
                       size = 3.4, colour = "grey10") +
    ggplot2::scale_fill_gradient2(low = "#2471A3", mid = "white",
                                  high = "#C0392B", midpoint = 0,
                                  limits = c(-1, 1), name = expression(rho)) +
    ggplot2::labs(
      title    = "Correlation of monthly excess returns",
      subtitle = paste0("Full sample, ", sample_label(cfg), "."),
      x = NULL, y = NULL, caption = source_caption(cfg)
    ) +
    theme_fma() +
    ggplot2::theme(panel.grid = ggplot2::element_blank())
}

#' Alpha estimates with HAC confidence intervals, by period.
plot_alpha_ci <- function(capm, cfg) {
  df <- capm
  df$lo <- df$alpha - 1.96 * df$alpha_se_hac
  df$hi <- df$alpha + 1.96 * df$alpha_se_hac

  ggplot2::ggplot(df, ggplot2::aes(x = stats::reorder(name, alpha), y = alpha)) +
    ggplot2::geom_hline(yintercept = 0, colour = "grey40", linewidth = 0.4) +
    ggplot2::geom_errorbar(ggplot2::aes(ymin = lo, ymax = hi),
                           width = 0.15, colour = "grey35") +
    ggplot2::geom_point(size = 2.6, colour = "#C0392B") +
    ggplot2::facet_wrap(~ period, ncol = 1, scales = "free_y") +
    ggplot2::coord_flip() +
    ggplot2::scale_y_continuous(labels = scales::percent_format(accuracy = 0.1)) +
    ggplot2::labs(
      title    = "Monthly CAPM alpha with 95% HAC confidence intervals",
      subtitle = "Intervals crossing zero indicate alpha is not statistically distinguishable from zero.",
      x = NULL, y = "Monthly alpha",
      caption = source_caption(cfg)
    ) +
    theme_fma()
}

#' Build and save every figure.
make_all_figures <- function(data, capm, roll, cfg, stability = NULL) {
  save_fig(plot_cumulative(data, cfg),           "01_cumulative_growth.png",   cfg)
  save_fig(plot_excess_returns(data, cfg),       "02_excess_returns.png",      cfg, height = 9)
  save_fig(plot_characteristic_lines(data, cfg), "03_characteristic_lines.png", cfg, height = 7.5)
  rb <- plot_rolling_beta(roll, cfg, stability)
  if (!is.null(rb)) save_fig(rb,                 "04_rolling_beta.png",        cfg, height = 7)
  save_fig(plot_correlation(data, cfg),               "05_correlation_matrix.png",  cfg, width = 7.5, height = 6)
  save_fig(plot_alpha_ci(capm, cfg),             "06_alpha_confidence.png",    cfg, height = 8)
  bs <- plot_beta_shift(stability, cfg)
  if (!is.null(bs)) save_fig(bs,                 "07_beta_shift.png",          cfg, height = 7)
  invisible(NULL)
}
